-- adds table for rsa's BSW scripts

DROP TABLE IF EXISTS `boss_spell_table`;
CREATE TABLE IF NOT EXISTS `boss_spell_table` (
  `entry`        MEDIUMINT(8) NOT NULL DEFAULT '0' COMMENT 'Creature entry',
  `spellID_N10`  MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Spell ID for 10 normal',
  `spellID_N25`  MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Spell ID for 25 normal',
  `spellID_H10`  MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Spell ID for 10 heroic',
  `spellID_H25`  MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Spell ID for 25 heroic',
  `timerMin_N10` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '15000' COMMENT 'Minimum timer for this spell (in ms.) for 10 normal',
  `timerMin_N25` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Minimum timer for this spell (in ms.) for 25 normal',
  `timerMin_H10` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Minimum timer for this spell (in ms.) for 10 heroic',
  `timerMin_H25` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Minimum timer for this spell (in ms.) for 25 heroic',
  `timerMax_N10` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '30000' COMMENT 'Maximum timer for this spell (in ms.) for 10 normal',
  `timerMax_N25` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Maximum timer for this spell (in ms.) for 25 normal',
  `timerMax_H10` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Maximum timer for this spell (in ms.) for 10 heroic',
  `timerMax_H25` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Maximum timer for this spell (in ms.) for 25 heroic',
  `data1`        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Various INT data for this spell or summon for 10 normal',
  `data2`        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Various INT data for this spell for 25 normal',
  `data3`        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Various INT data for this spell for 10 heroic',
  `data4`        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Various INT data for this spell for 25 heroic',
  `locData_x`    FLOAT NOT NULL DEFAULT '0' COMMENT 'Location X data for this spell',
  `locData_y`    FLOAT NOT NULL DEFAULT '0' COMMENT 'Location Y data for this spell',
  `locData_z`    FLOAT NOT NULL DEFAULT '0' COMMENT 'Location Z data for this spell',
  `varData`      MEDIUMINT(8) NOT NULL DEFAULT '0' COMMENT 'Special data field for this spell (basepoint for Aura, for example)',
  `StageMask_N`  SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Stage mask for this spell (don\'t used now)',
  `StageMask_H`  SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Stage mask for this spell - heroic mode (don\'t used now)',
  `CastType`     SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Type of cast (by enum BossSpellTableParameters)',
  `isVisualEffect` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Is spell is Visual effect only',
  `isBugged`     TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Is spell bugged and need override',
  `textEntry`    MEDIUMINT(8) NOT NULL DEFAULT '0' COMMENT 'Text from script_texts for this spell casting',
  `comment`      TEXT,
  PRIMARY KEY (`entry`,`spellID_N10`,`CastType`),
  INDEX `idx_entry`(`entry`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT 'Boss spell table by /dev/rsa';
